### ISSUE TITLE
Line chart for temperature

### ISSUE THREAD

**Issue by Marcus-Rosti** [Marcus-Rosti/CS_5010_Project#7]
Have a line chart displaying for temperature by day -- this one is a must

**Comment by imppilot** [comment]
I now have a working feature for this.  Let me know if there are any changes you want to see.

**Comment by imppilot** [comment]
New version is up.  This one appears a little busy- I'm thinking of dropping cloud coverage.  Opinions?

**Comment by Marcus-Rosti** [comment]
Ooo yeah super messy.  I bet only the last week would look pretty good

**Comment by nm1291** [comment]
Yep same here. 

![image](https://cloud.githubusercontent.com/assets/1998614/9189681/020ba1c0-3fba-11e5-80d3-823af67bda91.png)

Also from a user perspective, since temperature and the other two are in different units, it does not seem right to kind of have a comparision in the same graph. 

But you could show that Cloud Cover and Humidity is correlated maybe?

**Comment by imppilot** [comment]
Yeah, it felt weird making a graph with different units.  Given how all over the place the cloud data is, it's going to be hard to make comparisons.  Something I could try doing is averaging over a week, instead of a day.
